Mark Qt6Core5Compat as required when needed
Otherwise CMake will treat it as optional dependency and be happy
without it - even when compiling against Qt6 when it's needed for at
least QTextCodec.

src/kexiv2_p.cpp:25:10: fatal error: QTextCodec: No such file or directory
   25 | #include <QTextCodec>
      |          ^~~~~~~~~~~~